export type Mission = {
  id: string;
  number: string;
  category: string;
  severity: "CRÍTICA" | "ALTA";
  title: string;
  user: string;
  device: string;
  report: string;
  terminal: string[];
  hint: string;
  options: { label: string; correct: boolean; feedback: string }[];
  explanation: string;
  command: string;
};

type Seed = {
  id: string;
  category: string;
  severity: "CRÍTICA" | "ALTA";
  title: string;
  report: string;
  evidence: string[];
  hint: string;
  correct: string;
  wrong: [string, string];
  explanation: string;
  command: string;
};

const SEEDS: Seed[] = [
  { id:"apipa",category:"REDES",severity:"ALTA",title:"Un equipo obtiene una dirección 169.254",report:"Tengo red conectada, pero no puedo acceder a ningún servicio.",evidence:["ipconfig /all","IPv4: 169.254.34.18","Puerta de enlace: —","DHCP habilitado: Sí"],hint:"Una dirección APIPA indica que no llegó una concesión DHCP.",correct:"Revisar enlace, VLAN y DHCP; después renovar la concesión",wrong:["Cambiar el navegador predeterminado","Desactivar el antivirus"],explanation:"El fallo está en la obtención de configuración IP, antes de DNS o de las aplicaciones.",command:"ipconfig /release → ipconfig /renew"},
  { id:"dns",category:"SISTEMAS",severity:"ALTA",title:"La intranet funciona por IP, pero no por nombre",report:"La IP responde, aunque intranet.empresa.local no abre.",evidence:["ping 10.20.0.15 → RESPUESTA","nslookup intranet.empresa.local → NXDOMAIN"],hint:"Compara conectividad IP con resolución de nombres.",correct:"Revisar zona, registro DNS y caché del cliente",wrong:["Reinstalar el navegador","Reiniciar todos los switches"],explanation:"NXDOMAIN señala que DNS no encuentra el nombre solicitado.",command:"nslookup → revisar A/CNAME → ipconfig /flushdns"},
  { id:"phishing",category:"SEGURIDAD",severity:"CRÍTICA",title:"Correo urgente solicita credenciales",report:"Microsoft dice que mi cuenta se bloqueará y me pide iniciar sesión.",evidence:["De: soporte@micros0ft-verifica.net","Enlace: login-m365-seguro.example","Adjunto: formulario.zip"],hint:"Revisa dominio, urgencia, enlace y adjunto.",correct:"No abrir, reportar y comprobar si el usuario interactuó",wrong:["Abrirlo en modo incógnito","Responder solicitando confirmación"],explanation:"La prioridad es contener el riesgo y determinar si hubo exposición de credenciales.",command:"reportar → bloquear indicadores → revisar sesiones y MFA"},
  { id:"gateway",category:"REDES",severity:"ALTA",title:"El equipo ve la LAN, pero no sale a Internet",report:"Puedo abrir la impresora local, pero ninguna web.",evidence:["IPv4: 192.168.20.44/24","Gateway: 192.168.10.1","ping 192.168.20.1 → RESPUESTA"],hint:"La puerta de enlace debe estar en una red alcanzable desde el host.",correct:"Corregir la puerta de enlace mediante DHCP o configuración autorizada",wrong:["Cambiar el teclado","Vaciar la papelera"],explanation:"El gateway configurado pertenece a otra subred y no puede usarse como siguiente salto.",command:"ipconfig /all → validar gateway → renovar DHCP"},
  { id:"duplicate-ip",category:"REDES",severity:"ALTA",title:"La conexión aparece y desaparece",report:"Windows avisa de un conflicto de dirección IP.",evidence:["Evento TCP/IP: dirección duplicada","arp -a: misma IP asociada a dos MAC"],hint:"Dos dispositivos no deben usar la misma IPv4 en una subred.",correct:"Localizar los dos equipos y corregir la asignación DHCP o estática",wrong:["Desactivar DNS","Cambiar la resolución de pantalla"],explanation:"Un conflicto IP provoca respuestas ARP inconsistentes y pérdida intermitente de conectividad.",command:"arp -a → localizar MAC → corregir reserva o IP"},
  { id:"vlan",category:"REDES",severity:"ALTA",title:"Un puesto nuevo no llega a los servidores",report:"El cable funciona, pero el equipo recibe una red distinta.",evidence:["Puerto switch: access VLAN 30","VLAN prevista para el puesto: 20"],hint:"Un puerto access asigna el dispositivo a una VLAN concreta.",correct:"Validar autorización y configurar el puerto en la VLAN correcta",wrong:["Asignar una IP pública","Desinstalar el controlador gráfico"],explanation:"El puerto está en un dominio lógico diferente al previsto.",command:"show vlan → show interface switchport → corregir VLAN"},
  { id:"trunk",category:"REDES",severity:"CRÍTICA",title:"Varias VLAN dejan de cruzar entre switches",report:"Tras cambiar un enlace, varias plantas pierden servicios.",evidence:["Trunk allowed VLANs: 10,20","VLAN afectada: 30"],hint:"Un trunk solo transporta las VLAN permitidas.",correct:"Añadir la VLAN autorizada al trunk y comprobar ambos extremos",wrong:["Crear usuarios locales","Reiniciar las impresoras"],explanation:"La VLAN 30 no está incluida en la lista permitida del enlace troncal.",command:"show interfaces trunk → validar allowed VLANs"},
  { id:"loop",category:"REDES",severity:"CRÍTICA",title:"La red se satura tras conectar un latiguillo",report:"Todo va muy lento y los switches parpadean sin parar.",evidence:["Broadcast rate: 96%","STP topology changes: elevados"],hint:"Un bucle de capa 2 puede generar una tormenta de broadcast.",correct:"Aislar el enlace sospechoso y revisar STP antes de reconectar",wrong:["Cambiar el servidor DNS","Formatear un portátil"],explanation:"La contención rápida evita que el bucle siga afectando a toda la LAN.",command:"aislar puerto → revisar STP → corregir cableado"},
  { id:"wifi-signal",category:"REDES",severity:"ALTA",title:"El Wi‑Fi falla en una sala concreta",report:"Cerca de la puerta funciona; al fondo se corta.",evidence:["RSSI: -82 dBm","Reintentos: 38%","Banda: 5 GHz"],hint:"La cobertura y la interferencia deben medirse en el lugar afectado.",correct:"Realizar medición, revisar ubicación del AP y plan de cobertura",wrong:["Desactivar el firewall corporativo","Cambiar la contraseña de todos"],explanation:"La señal es débil; primero se corrige cobertura, capacidad o interferencias.",command:"medir RSSI → revisar canal/AP → validar cobertura"},
  { id:"wifi-channel",category:"REDES",severity:"ALTA",title:"La Wi‑Fi tiene buena señal, pero poco rendimiento",report:"Aparece máxima cobertura, aunque las videollamadas se congelan.",evidence:["RSSI: -48 dBm","Canal: 6","Redes vecinas en canal 6: 14"],hint:"Buena señal no significa un canal libre.",correct:"Analizar espectro y ajustar el plan de canales",wrong:["Cambiar la IP del servidor","Eliminar perfiles de usuario"],explanation:"La congestión y las interferencias reducen el tiempo de aire disponible.",command:"survey Wi‑Fi → seleccionar canal → verificar rendimiento"},
  { id:"cable",category:"HARDWARE",severity:"ALTA",title:"El adaptador Ethernet aparece desconectado",report:"No se enciende ninguna luz junto al conector.",evidence:["Estado: cable de red desconectado","LED NIC: apagado","LED switch: apagado"],hint:"Empieza por la capa física.",correct:"Probar latiguillo, roseta y puerto conocido antes de cambiar software",wrong:["Modificar DNS","Restaurar Windows"],explanation:"Sin enlace físico no tiene sentido diagnosticar capas superiores.",command:"cable → roseta → puerto switch → NIC"},
  { id:"speed-duplex",category:"REDES",severity:"ALTA",title:"Un único equipo transfiere archivos muy despacio",report:"La red funciona, pero copiar al servidor tarda muchísimo.",evidence:["NIC: 100 Mbps half duplex","Switch: 1 Gbps full duplex","Errores CRC: elevados"],hint:"Compara velocidad y dúplex en ambos extremos.",correct:"Corregir negociación y revisar cableado",wrong:["Crear otro usuario","Cambiar el fondo de escritorio"],explanation:"El desajuste de dúplex produce colisiones y retransmisiones.",command:"auto-negociación → validar cable → comprobar errores"},
  { id:"routing",category:"REDES",severity:"CRÍTICA",title:"Una sede no alcanza una red remota",report:"Internet funciona, pero la aplicación de la central no.",evidence:["tracert se detiene en router de sede","Tabla de rutas: falta 10.60.0.0/16"],hint:"El router necesita una ruta hacia cada red no conectada.",correct:"Añadir o recuperar la ruta por el procedimiento de cambios",wrong:["Cambiar el monitor","Vaciar caché del navegador"],explanation:"Sin una ruta, el router no conoce el siguiente salto hacia la red remota.",command:"traceroute → tabla de rutas → validar siguiente salto"},
  { id:"nat",category:"REDES",severity:"ALTA",title:"La LAN navega, salvo una nueva subred",report:"Los equipos nuevos llegan al router, pero no a Internet.",evidence:["Ruta interna: correcta","NAT inside sources: no incluye 192.168.40.0/24"],hint:"Las redes privadas necesitan una traducción autorizada para salir.",correct:"Incluir la subred en la política NAT y verificar retorno",wrong:["Publicar el servidor DHCP","Desactivar las actualizaciones"],explanation:"La nueva subred no está cubierta por la regla de traducción.",command:"revisar ACL NAT → añadir subred → probar salida"},
  { id:"firewall",category:"SEGURIDAD",severity:"ALTA",title:"Una aplicación deja de conectar tras endurecer reglas",report:"El servidor responde a ping, pero el puerto de la aplicación no.",evidence:["ping: correcto","Test-NetConnection puerto 8443: bloqueado","Log firewall: DENY"],hint:"Valida el flujo exacto sin desactivar toda la protección.",correct:"Crear una regla mínima para origen, destino y puerto autorizados",wrong:["Desactivar completamente el firewall","Abrir todos los puertos"],explanation:"El principio de mínimo privilegio permite el servicio sin ampliar innecesariamente el riesgo.",command:"identificar flujo → regla mínima → registrar y probar"},
  { id:"vpn",category:"REDES",severity:"ALTA",title:"La VPN conecta, pero no abre recursos internos",report:"El túnel figura activo, aunque no puedo llegar al servidor.",evidence:["Handshake: correcto","AllowedIPs: 10.10.0.0/24","Servidor: 10.20.0.15"],hint:"El túnel solo enruta las redes incluidas.",correct:"Añadir la red autorizada a las rutas del túnel y revisar retorno",wrong:["Compartir la clave privada","Desactivar el cifrado"],explanation:"La red del servidor no está incluida en las rutas de la VPN.",command:"revisar AllowedIPs/rutas → validar firewall y retorno"},
  { id:"dhcp-scope",category:"SISTEMAS",severity:"CRÍTICA",title:"Los nuevos equipos no reciben IP",report:"Los puestos antiguos funcionan, pero los recién conectados no.",evidence:["Ámbito DHCP: 192.168.50.10-200","Direcciones libres: 0","Leases activos: 191"],hint:"Un ámbito agotado no puede entregar nuevas concesiones.",correct:"Liberar concesiones obsoletas o ampliar el ámbito con planificación",wrong:["Cambiar el servidor web","Reinstalar Office"],explanation:"El pool DHCP se ha quedado sin direcciones disponibles.",command:"revisar leases → limpiar reservas → ampliar ámbito"},
  { id:"dhcp-relay",category:"REDES",severity:"ALTA",title:"DHCP funciona en una VLAN, pero no en otra",report:"Solo la nueva VLAN obtiene direcciones APIPA.",evidence:["Servidor DHCP en VLAN 10","Clientes afectados en VLAN 40","Relay VLAN 40: no configurado"],hint:"Los broadcasts DHCP no cruzan routers por sí solos.",correct:"Configurar el relay DHCP hacia el servidor autorizado",wrong:["Duplicar el servidor DNS","Usar IP públicas en los clientes"],explanation:"La VLAN remota necesita reenviar las solicitudes DHCP al servidor.",command:"configurar helper-address → validar ámbito → probar DORA"},
  { id:"ad-dns",category:"SISTEMAS",severity:"CRÍTICA",title:"Un equipo no puede unirse al dominio",report:"Dice que no encuentra el controlador de dominio.",evidence:["DNS cliente: 8.8.8.8","Dominio: empresa.local","Consulta SRV: no encontrada"],hint:"Active Directory depende de sus registros DNS internos.",correct:"Configurar el DNS corporativo y comprobar registros SRV",wrong:["Abrir RDP a Internet","Crear el usuario solo en local"],explanation:"Un DNS público no conoce la zona interna ni los servicios del dominio.",command:"configurar DNS AD → nslookup SRV → unir al dominio"},
  { id:"clock",category:"SISTEMAS",severity:"ALTA",title:"El dominio rechaza credenciales correctas",report:"La contraseña funciona en otro equipo.",evidence:["Hora cliente: 10:42","Hora DC: 10:31","Kerberos: clock skew too great"],hint:"Kerberos tolera solo una diferencia de tiempo limitada.",correct:"Corregir la sincronización horaria y revisar la fuente NTP",wrong:["Eliminar la cuenta del usuario","Desactivar Kerberos"],explanation:"El desfase impide validar de forma segura los tickets de autenticación.",command:"w32tm /query /status → resincronizar → validar NTP"},
  { id:"gpo",category:"SISTEMAS",severity:"ALTA",title:"Una política no se aplica a un grupo",report:"Otros departamentos sí reciben la configuración.",evidence:["gpresult: GPO denegada","Motivo: filtrado de seguridad"],hint:"Revisa vínculo, ámbito, permisos y filtrado.",correct:"Corregir el filtrado o pertenencia siguiendo el diseño de grupos",wrong:["Editar el registro manualmente en todos los PC","Desactivar el controlador de dominio"],explanation:"La GPO existe, pero el grupo afectado no tiene el ámbito necesario.",command:"gpresult /h → revisar OU y filtro → gpupdate"},
  { id:"permissions",category:"SISTEMAS",severity:"ALTA",title:"Un usuario abre una carpeta, pero no puede modificarla",report:"Puedo leer documentos, aunque no guardar cambios.",evidence:["Share: Change","NTFS: Read & Execute","Grupo: Equipo-Proyecto"],hint:"Por red se combinan permisos de recurso compartido y NTFS.",correct:"Asignar Modify al grupo correcto aplicando mínimo privilegio",wrong:["Dar Control total a Todos","Compartir la contraseña del administrador"],explanation:"El permiso NTFS efectivo limita la escritura aunque el recurso permita cambios.",command:"revisar permisos efectivos → ajustar grupo → probar"},
  { id:"disk-full",category:"SISTEMAS",severity:"CRÍTICA",title:"Un servidor deja de generar informes",report:"La aplicación muestra errores al guardar.",evidence:["Unidad C: 99.8% usada","Log: no space left on device"],hint:"Confirma consumo y crecimiento antes de borrar.",correct:"Identificar datos seguros para archivar o limpiar y ampliar capacidad si procede",wrong:["Borrar carpetas del sistema al azar","Desactivar el registro de auditoría"],explanation:"La falta de espacio afecta aplicaciones y sistema; la limpieza debe ser controlada.",command:"medir uso → localizar crecimiento → limpiar/archivar → alertar"},
  { id:"smart",category:"HARDWARE",severity:"CRÍTICA",title:"El disco muestra errores y ruidos",report:"El equipo se bloquea al abrir archivos.",evidence:["SMART: Reallocated sectors increasing","Evento: bad block"],hint:"Preserva los datos antes de someter el disco a más carga.",correct:"Realizar copia prioritaria y sustituir el disco",wrong:["Desfragmentar repetidamente","Ignorar hasta que deje de arrancar"],explanation:"Los indicadores muestran degradación física y riesgo de pérdida.",command:"copia segura → diagnóstico del fabricante → sustitución"},
  { id:"ram",category:"HARDWARE",severity:"ALTA",title:"Aparecen bloqueos y pantallazos aleatorios",report:"Los errores cambian cada vez y no hay un programa concreto.",evidence:["Windows Memory Diagnostic: hardware problems detected","Errores: MEMORY_MANAGEMENT"],hint:"Los fallos variables pueden proceder de memoria inestable.",correct:"Probar módulos de RAM y ranuras de forma controlada",wrong:["Cambiar DNS","Desactivar las copias de seguridad"],explanation:"La evidencia apunta a errores de memoria y requiere aislar el módulo defectuoso.",command:"diagnóstico RAM → probar módulos → revisar compatibilidad"},
  { id:"overheating",category:"HARDWARE",severity:"ALTA",title:"El portátil se apaga bajo carga",report:"Durante una videollamada se calienta mucho y se apaga.",evidence:["CPU: 98 °C","Thermal throttling: activo","Ventilador: 0 RPM"],hint:"Una protección térmica puede apagar el equipo.",correct:"Apagar, revisar ventilación, ventilador y pasta térmica",wrong:["Forzar el rendimiento máximo","Tapar las rejillas para reducir ruido"],explanation:"Seguir utilizándolo a esa temperatura puede dañar componentes.",command:"apagar → limpiar/revisar ventilación → prueba térmica"},
  { id:"update",category:"SISTEMAS",severity:"ALTA",title:"Una actualización queda atascada",report:"El equipo reinicia y vuelve al mismo porcentaje.",evidence:["Windows Update: 0x800f081f","DISM: source files could not be found"],hint:"Hay que reparar componentes sin borrar datos.",correct:"Revisar registros, reparar imagen y reintentar con una fuente válida",wrong:["Cortar la corriente durante la instalación","Formatear sin copia ni diagnóstico"],explanation:"El código señala componentes ausentes o dañados en el almacén.",command:"DISM /RestoreHealth → sfc /scannow → actualizar"},
  { id:"service",category:"SISTEMAS",severity:"ALTA",title:"Una aplicación no arranca después de reiniciar",report:"La web interna muestra servicio no disponible.",evidence:["systemctl status app: failed","journalctl: permission denied al abrir /var/app/data"],hint:"El registro explica por qué falló el servicio.",correct:"Corregir propietario o permisos mínimos y reiniciar el servicio",wrong:["Aplicar chmod 777 a todo el servidor","Desactivar el firewall"],explanation:"El proceso no puede acceder a sus datos por permisos incorrectos.",command:"journalctl -u app → corregir permisos → systemctl restart"},
  { id:"certificate",category:"SEGURIDAD",severity:"ALTA",title:"El navegador avisa de certificado caducado",report:"La intranet funcionaba ayer y hoy aparece como no segura.",evidence:["Certificate expired","Not After: fecha de ayer","Nombre: intranet.empresa.local"],hint:"Comprueba fecha, cadena y nombre antes de sustituir.",correct:"Renovar el certificado, instalar la cadena y verificar el servicio",wrong:["Indicar a todos que ignoren el aviso","Usar HTTP permanentemente"],explanation:"El certificado ya no está dentro de su periodo de validez.",command:"inventario → renovar → desplegar → comprobar TLS"},
  { id:"backup",category:"CONTINUIDAD",severity:"CRÍTICA",title:"Una copia termina correctamente, pero no restaura",report:"El trabajo aparece en verde, aunque el archivo recuperado está corrupto.",evidence:["Backup job: success","Restore test: checksum mismatch"],hint:"Una copia no está verificada hasta probar la restauración.",correct:"Investigar integridad, generar una copia válida y repetir prueba",wrong:["Seguir confiando solo en el indicador verde","Eliminar las demás copias"],explanation:"La restauración de prueba ha revelado que el objetivo de recuperación no se cumple.",command:"verificar checksums → nueva copia → prueba de restore"},
  { id:"ransomware",category:"SEGURIDAD",severity:"CRÍTICA",title:"Archivos compartidos aparecen cifrados",report:"Veo extensiones extrañas y una nota de rescate.",evidence:["Muchos archivos renombrados","Proceso desconocido escribiendo en red","Nota: RECOVER_FILES.txt"],hint:"La velocidad de contención es prioritaria.",correct:"Aislar equipos y recurso afectado, preservar evidencia y activar respuesta",wrong:["Pagar inmediatamente sin avisar","Conectar discos de copia al equipo afectado"],explanation:"Hay que detener propagación, evaluar alcance y recuperar desde copias seguras.",command:"aislar → escalar → preservar → erradicar → restaurar"},
  { id:"malware",category:"SEGURIDAD",severity:"CRÍTICA",title:"El antivirus detecta ejecución sospechosa",report:"Apareció una ventana extraña tras abrir un adjunto.",evidence:["EDR: powershell encoded command","Conexión: dominio recién creado"],hint:"No borres evidencias antes de conocer el alcance.",correct:"Aislar el equipo, avisar y seguir el procedimiento de respuesta",wrong:["Desactivar el EDR","Continuar trabajando con normalidad"],explanation:"La combinación de ejecución ofuscada y comunicación externa requiere contención.",command:"aislar host → recopilar indicadores → analizar → recuperar"},
  { id:"mfa",category:"SEGURIDAD",severity:"CRÍTICA",title:"Un usuario recibe avisos MFA que no inició",report:"El móvil pide aprobar accesos continuamente.",evidence:["Origen: país no habitual","20 solicitudes en 3 minutos"],hint:"La fatiga MFA intenta que el usuario apruebe por error.",correct:"Rechazar, bloquear sesiones, cambiar credenciales y revisar la cuenta",wrong:["Aprobar para que dejen de llegar","Desactivar MFA permanentemente"],explanation:"Las solicitudes no iniciadas indican credenciales posiblemente comprometidas.",command:"rechazar → revocar sesiones → cambiar clave → revisar MFA"},
  { id:"bitlocker",category:"SEGURIDAD",severity:"ALTA",title:"Un portátil solicita clave de recuperación",report:"Después de una actualización de firmware no arranca con normalidad.",evidence:["BitLocker Recovery","PCR values changed"],hint:"No improvises: utiliza el proceso autorizado de recuperación.",correct:"Verificar identidad y obtener la clave del repositorio corporativo",wrong:["Publicar la clave en un chat abierto","Formatear sin comprobar copias"],explanation:"Un cambio medido por TPM puede activar la protección de BitLocker.",command:"validar usuario/equipo → recuperar clave → revisar evento"},
  { id:"raid",category:"CONTINUIDAD",severity:"CRÍTICA",title:"Un RAID aparece degradado",report:"El servidor sigue activo, pero muestra un disco fallido.",evidence:["RAID 5: DEGRADED","Disk 2: FAILED","Hot spare: none"],hint:"La tolerancia está reducida; otro fallo puede causar pérdida.",correct:"Confirmar copia, sustituir el disco compatible y supervisar reconstrucción",wrong:["Extraer varios discos a la vez","Considerar RAID como única copia"],explanation:"El servicio continúa, pero la redundancia está comprometida.",command:"verificar backup → identificar disco → reemplazar → monitorizar"},
  { id:"vm-storage",category:"VIRTUALIZACIÓN",severity:"CRÍTICA",title:"Varias máquinas virtuales se pausan",report:"Los servidores virtuales muestran errores de escritura.",evidence:["Datastore usage: 100%","VM state: paused-critical"],hint:"Un recurso compartido puede afectar a muchas cargas.",correct:"Liberar o ampliar almacenamiento de forma controlada y reanudar",wrong:["Borrar discos virtuales al azar","Reiniciar todas las VM repetidamente"],explanation:"El datastore lleno impide escrituras y afecta simultáneamente a varias máquinas.",command:"medir datastore → liberar/ampliar → validar VM"},
  { id:"snapshot",category:"VIRTUALIZACIÓN",severity:"ALTA",title:"Una máquina virtual pierde rendimiento",report:"Desde hace semanas cada operación de disco es más lenta.",evidence:["Snapshots: 14","Snapshot más antiguo: 93 días","Delta disk: 280 GB"],hint:"Un snapshot no es una copia permanente.",correct:"Comprobar backup y consolidar snapshots con ventana controlada",wrong:["Crear más snapshots","Borrar archivos delta manualmente"],explanation:"Una cadena larga aumenta consumo y penaliza E/S.",command:"validar backup → consolidar → comprobar espacio/rendimiento"},
  { id:"docker",category:"SISTEMAS",severity:"ALTA",title:"Un contenedor reinicia continuamente",report:"La aplicación nunca llega a estar disponible.",evidence:["State: restarting","Log: connection refused db:5432","Restart count: 87"],hint:"El log apunta a una dependencia, no al motor de contenedores.",correct:"Verificar red, nombre y disponibilidad de la base de datos",wrong:["Eliminar todos los volúmenes","Exponer la base de datos a Internet"],explanation:"El contenedor falla porque no puede conectar con su dependencia.",command:"docker logs → revisar red/DNS → validar dependencia"},
  { id:"printer",category:"SOPORTE",severity:"ALTA",title:"Una impresora de red figura sin conexión",report:"Nadie del departamento puede imprimir.",evidence:["ping impresora: sin respuesta","Switch port: down","Cola: 38 trabajos"],hint:"Separa conectividad del estado de la cola.",correct:"Restaurar enlace de la impresora y después gestionar la cola",wrong:["Reinstalar Office en todos los PC","Cambiar el DNS público"],explanation:"El puerto está caído; primero se recupera conectividad y luego el servicio.",command:"alimentación/cable → puerto → IP → cola de impresión"},
  { id:"spooler",category:"SOPORTE",severity:"ALTA",title:"Un solo equipo no imprime",report:"La impresora responde y los demás sí pueden usarla.",evidence:["ping: correcto","Spooler: stopped","Cola local: trabajo corrupto"],hint:"El alcance está limitado al cliente.",correct:"Limpiar el trabajo bloqueado y reiniciar el servicio de impresión",wrong:["Reiniciar el switch central","Cambiar la IP de la impresora"],explanation:"La red y la impresora funcionan; el fallo está en la cola local.",command:"detener spooler → limpiar cola → iniciar → probar"},
  { id:"email-quota",category:"SOPORTE",severity:"ALTA",title:"Un buzón no puede enviar ni recibir",report:"Outlook avisa de que el almacenamiento está lleno.",evidence:["Mailbox quota: 100%","Largest folder: Deleted Items"],hint:"Confirma cuota y política de retención.",correct:"Archivar o limpiar según política y revisar crecimiento del buzón",wrong:["Desactivar el antivirus","Crear una cuenta compartida sin autorización"],explanation:"La cuota alcanzada impide nuevas operaciones de correo.",command:"medir carpetas → archivar/retener → validar flujo"},
  { id:"internet",category:"REDES",severity:"ALTA",title:"Hay acceso local, pero no a Internet",report:"La intranet funciona y el router responde, pero ninguna IP externa.",evidence:["ping gateway: correcto","ping 1.1.1.1: timeout","WAN router: down"],hint:"Internet es una interconexión de redes; comprueba el límite LAN/WAN.",correct:"Revisar enlace WAN y escalar al proveedor con evidencias",wrong:["Reinstalar cada navegador","Cambiar permisos de carpetas"],explanation:"La LAN funciona y el fallo aparece en la salida WAN o en el proveedor.",command:"LAN → gateway → WAN → proveedor"},
];

const CONTEXTS = [
  { person:"Laura · Contabilidad",device:"PC-CONT-03",place:"Contabilidad" },
  { person:"Mario · RRHH",device:"PORTATIL-RRHH-07",place:"Recursos Humanos" },
  { person:"Sara · Dirección",device:"LAPTOP-DIR-01",place:"Dirección" },
  { person:"Álex · Ventas",device:"PC-VENTAS-12",place:"Ventas" },
  { person:"Noa · Operaciones",device:"EQUIPO-OPS-05",place:"Operaciones" },
  { person:"Lucía · Marketing",device:"LAPTOP-MKT-09",place:"Marketing" },
  { person:"Hugo · Almacén",device:"PDA-ALMACEN-14",place:"Almacén" },
  { person:"Elena · Compras",device:"PC-COMPRAS-04",place:"Compras" },
  { person:"Daniel · Desarrollo",device:"WORKSTATION-DEV-08",place:"Desarrollo" },
  { person:"Irene · Atención",device:"MINIPC-ATC-16",place:"Atención al cliente" },
  { person:"Samuel · Logística",device:"PORTATIL-LOG-06",place:"Logística" },
  { person:"Marta · Administración",device:"PC-ADMIN-11",place:"Administración" },
];

export const QUESTION_BANK: Mission[] = SEEDS.flatMap((seed, seedIndex) =>
  CONTEXTS.map((context, variant) => {
    const choices = [
      { label: seed.correct, correct: true, feedback: `Correcto. ${seed.explanation}` },
      { label: seed.wrong[0], correct: false, feedback: "Esa acción no explica las evidencias o aumenta el riesgo." },
      { label: seed.wrong[1], correct: false, feedback: "No es una intervención proporcionada ni segura para este síntoma." },
    ];
    const rotated = [...choices.slice(variant % 3), ...choices.slice(0, variant % 3)];
    const index = seedIndex * CONTEXTS.length + variant + 1;
    return {
      id: `${seed.id}-${variant + 1}`,
      number: `INC-${String(index).padStart(3, "0")}`,
      category: seed.category,
      severity: seed.severity,
      title: `${seed.title} · ${context.place}`,
      user: context.person,
      device: context.device,
      report: seed.report,
      terminal: seed.evidence,
      hint: seed.hint,
      options: rotated,
      explanation: seed.explanation,
      command: seed.command,
    };
  }),
).slice(0, 500);
